# Generated by Django 4.2.7 on 2023-11-17 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('example', '0003_dataset_contrast_dataset_entropy_dataset_homogeneity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageQuery',
        ),
    ]
